### ISSUE TITLE
keep using \parselify

### ISSUE THREAD

**Issue by entorb** [yeKcim/hpmor#3]
I really like the \parselify logic https://github.com/yeKcim/hpmor/blob/d6a02fcb301b13bbb72d53d12c003044e00616be/hp-markup.tex#L11-L16
If conversion to ebook is a problem, you could maybe use a preprocessing like I did in my ebook converter script: 
https://github.com/rjl20/hpmor/blob/7589ccc3d79984726db99fac50f0061b31824184/ebook/1_latex2html.py#L555
and https://github.com/rjl20/hpmor/blob/7589ccc3d79984726db99fac50f0061b31824184/ebook/1_latex2html.py#L619

**Comment by yeKcim** [comment]
parselify is great but in french I don't find a good way to automatically parselify text.

S sounds like in snake, but in some words  sounds like zoro. If you double all S it's hard to read, so I let "zoro" words with only one S. Also, some T or C sounds like in snake (ex:potion/cédille) so I’ve sometimes add a ç (sounds like in snake too) to T or C,…  

parselify seems too complicated to automated in french (for me)

**Comment by entorb** [comment]
ok, understood
