### ISSUE TITLE
ebook creation fails in chapter 64

### ISSUE THREAD

**Issue by entorb** [yeKcim/hpmor#5]
Warning: ./chapters/hpmor-chapter-064.tex.
Warning: consider using --makeatletter if the result is not compilable.

Error at "source" (line 13467, column 13):
unexpected \chapter
expecting \end{document}
\clearpage{}\partchapter{Travail de groupe}{II}

here a small suggestion for adding more annotations to make debugging easier
https://github.com/entorb/hpmor-de/blob/fr-ebook-v2/ebook/2epub.sh

**Comment by yeKcim** [comment]
Strange, I’ve created epub with the script with no bug 🤨 I have to investigate

**Comment by entorb** [comment]
hm, if working fine, you could uncomment this line: https://github.com/yeKcim/hpmor/blob/19a749c310e41937d19c264f667b5fe2e3108de6/make_ebooks.sh#L4

**Comment by entorb** [comment]
found my problem: outdated linux and pandoc versions.
